export default {
    CHANGE_ITEMS: 'CHANGE_ITEMS',
    CHANGE_SEARCH_TEXT: 'CHANGE_SEARCH_TEXT',
    CHANGE_MIN_PRICE: 'CHANGE_MIN_PRICE',
    CHANGE_MAX_PRICE: 'CHANGE_MAX_PRICE',
    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
    INCREAMENT_CART_ITEMS: 'INCREAMENT_CART_ITEMS',
    DECREAMENT_CART_ITEMS: 'DECREAMENT_CART_ITEMS'
}